name: Action GO

on:
  push:
    branches:
      - master
      - feat/gitaction

  pull_request:
    branches:
      - master

jobs:
  My-Action: 
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World
        run: echo "Hello World"